---
title: Schedule
draft: false
draft-mode: visible
---

Here's your roadmap for the semester!

- Class
    - {{< fa chalkboard >}} Instructor-led lecture: concepts, theory and foundations.
    - {{< fa code >}} Hands-on exercises with guidance.
- Homework ({{< fa laptop-code >}})
    - Assigned at the end of class.
    - Due 7 days later (Mon → next Mon 13:30; Thu → next Thu 18:45)
- Additional resources ({{< fa book >}})
    - Further readings and online learning resources


### Semester Schedule

| Week | Topic | Monday | Thursday | Slides | Exercise | Homework | Resources |
|:----:|:-----|:------|:--------|:------:|:---:|:------:|:------:|
| 1    | Course Roadmap & Research Workflow | Feb 09  | Feb 12  | [<i class="fa fa-chalkboard" style="color: black; font-weight: bold;"></i>](slides/week1.html) |  [<i class="fa fa-code" style="color: black; font-weight: bold;"></i>](https://github.com/qmir-2026/qmir-2026.github.io/blob/main/lab/quarto-welcome.qmd)  | [{{< fa laptop-code >}}]{style="color: lightgray"} | [<i class="fa fa-book" style="color: black; font-weight: bold;"></i>](resources/01_resources.qmd) |

#### Block I: Scientific Programming Fundamentals

| Week | Topic | Monday | Thursday | Slides | Exercise | Homework | Resources |
|:----:|:------|:------|:--------|:------:|:---:|:------:|:------:|
| 2    | Reproducible Research with R, Quarto & Git | Feb 16 | Feb 19 | [<i class="fa fa-chalkboard" style="color: black; font-weight: bold;"></i>](slides/week2.html) | [{{< fa code >}}]{style="color: lightgray"}  | [{{< fa laptop-code >}}]{style="color: lightgray"} | [<i class="fa fa-book" style="color: black; font-weight: bold;"></i>](resources/02_resources.qmd) |
| 3    | R Fundamentals: Data Types & Structures | Feb 23 | Feb 26 | [<i class="fa fa-chalkboard" style="color: black; font-weight: bold;"></i>](slides/week3.html) | [<i class="fa fa-code" style="color: black; font-weight: bold;"></i>](https://github.com/qmir-2026/lab-w03)  | <span class="hw-visible"> Mon [<i class="fa fa-laptop-code" style="color: black; font-weight: bold;"></i>](https://classroom.github.com/a/bPTMyldB)<br>Thu [<i class="fa fa-laptop-code" style="color: black; font-weight: bold;"></i>](https://classroom.github.com/a/Ks-bAtDM) </span>   | [<i class="fa fa-book" style="color: black; font-weight: bold;"></i>](resources/03_resources.qmd) |
| 4    | Tidy Data: Wrangling & Visualization | Mar 02 | Mar 05 | [<i class="fa fa-chalkboard" style="color: black; font-weight: bold;"></i>](slides/week4.html) | [<i class="fa fa-code" style="color: black; font-weight: bold;"></i>](https://github.com/qmir-2026/lab-w04)  | <span class="hw-visible"> Mon [<i class="fa fa-laptop-code" style="color: black; font-weight: bold;"></i>](https://classroom.github.com/a/YNORKHon)<br>Thu [<i class="fa fa-laptop-code" style="color: black; font-weight: bold;"></i>](https://classroom.github.com/a/Xi0W-sFb) | [<i class="fa fa-book" style="color: black; font-weight: bold;"></i>](resources/04_resources.qmd) |
| 5    | Reshaping, Merging & Data Visualization | Mar 09 | Mar 12 | [<i class="fa fa-chalkboard" style="color: black; font-weight: bold;"></i>](slides/week5.html) | [<i class="fa fa-code" style="color: black; font-weight: bold;"></i>](https://github.com/qmir-2026/lab-w05)  | <span class="hw-visible"> Mon [<i class="fa fa-laptop-code" style="color: black; font-weight: bold;"></i>](https://classroom.github.com/a/7YkX6uNE)<br>Thu [<i class="fa fa-laptop-code" style="color: black; font-weight: bold;"></i>](https://classroom.github.com/a/EDvwDgEf) | [<i class="fa fa-book" style="color: black; font-weight: bold;"></i>](resources/05_resources.qmd) |

#### Block II: The Logic of Bayesian Inference

| Week | Topic | Monday | Thursday | Slides | Exercise | Homework | Resources |
|:----:|:-----|:------|:--------|:------:|:----:|:------:|:------:|
| 6    | Probability, Simulation & Bayes’ Theorem | Mar 16 | Mar 19 | [<i class="fa fa-chalkboard" style="color: black; font-weight: bold;"></i>](slides/week6.qmd) | [{{< fa code >}}]{style="color: lightgray"}  | <span class="hw-visible"> Mon [<i class="fa fa-laptop-code" style="color: black; font-weight: bold;"></i>](https://classroom.github.com/a/o5ie5qMP)<br>Thu [<i class="fa fa-laptop-code" style="color: black; font-weight: bold;"></i>](https://classroom.github.com/a/f9Q9f8Ua) | [<i class="fa fa-book" style="color: black; font-weight: bold;"></i>](resources/06_resources.qmd) |
| 7    | Markov Chain Monte Carlo | Mar 23 | Mar 26 | [<i class="fa fa-chalkboard" style="color: black; font-weight: bold;"></i>](slides/week7.qmd) | [{{< fa code >}}]{style="color: lightgray"} |  <span class="hw-visible"> Mon [<i class="fa fa-laptop-code" style="color: black; font-weight: bold;"></i>](https://classroom.github.com/a/J_tyxs8g)<br>Thu [<i class="fa fa-laptop-code" style="color: black; font-weight: bold;"></i>](https://classroom.github.com/a/7AqmTMs3) | [<i class="fa fa-book" style="color: black; font-weight: bold;"></i>](resources/07_resources.qmd) |

#### Block III: Applied Data Analysis

| Week | Topic | Monday | Thursday | Slides | Exercise | Homework | Resources |
|:----:|:-----|:------|:--------|:------:|:---:|:------:|:------:|
| 8    | Bivariate Linear Regression    | Apr 13 | Apr 16 | [<i class="fa fa-chalkboard" style="color: black; font-weight: bold;"></i>](slides/week8.qmd) | [{{< fa code >}}]{style="color: lightgray"}  | <span class="hw-visible"> Mon [<i class="fa fa-laptop-code" style="color: black; font-weight: bold;"></i>](https://classroom.github.com/a/lw0Ewijh)<br>Thu [<i class="fa fa-laptop-code" style="color: black; font-weight: bold;"></i>](https://classroom.github.com/a/gtaSEMcO) </span> | [<i class="fa fa-book" style="color: black; font-weight: bold;"></i>](resources/08_resources.qmd) |
| 9    | Multivariate Regression | Apr 20 | Apr 23 | [<i class="fa fa-chalkboard" style="color: black; font-weight: bold;"></i>](slides/week9.qmd) | [<i class="fa fa-code" style="color: black; font-weight: bold;"></i>](lab/week9_lab.qmd)  | <span class="hw-visible"> Mon [<i class="fa fa-laptop-code" style="color: black; font-weight: bold;"></i>](https://classroom.github.com/a/F4z8dLAo)<br>Thu [<i class="fa fa-laptop-code" style="color: black; font-weight: bold;"></i>](https://classroom.github.com/a/jJS_ouIM) </span> | [<i class="fa fa-book" style="color: black; font-weight: bold;"></i>](resources/09_resources.qmd) |
| 10   | Interactions | Apr 27 | Apr 30 |[<i class="fa fa-chalkboard" style="color: black; font-weight: bold;"></i>](slides/week10.qmd) | [<i class="fa fa-code" style="color: black; font-weight: bold;"></i>](lab/week10_lab.qmd)  | <span class="hw-visible"> Mon [<i class="fa fa-laptop-code" style="color: black; font-weight: bold;"></i>](https://classroom.github.com/a/fYsza2Mp) | [<i class="fa fa-book" style="color: black; font-weight: bold;"></i>](resources/10_resources.qmd) |
| 11   | Modeling Binary Outcomes | May 04 | May 07 | [{{< fa chalkboard >}}]{style="color: lightgray"} | [{{< fa code >}}]{style="color: lightgray"}  | [{{< fa laptop-code >}}]{style="color: lightgray"} | <i class="fa fa-book" style="color: lightgray; font-weight: bold;"></i> |
| 12   | Multilevel Models & Partial Pooling  | May 11 | May 21 | [{{< fa chalkboard >}}]{style="color: lightgray"} | [{{< fa code >}}]{style="color: lightgray"}  | [{{< fa laptop-code >}}]{style="color: lightgray"} | <i class="fa fa-book" style="color: lightgray; font-weight: bold;"></i> |
| 13   | Beyond the Course: Applying What You've Learned | May 18 | May 28 | [{{< fa chalkboard >}}]{style="color: lightgray"} | [{{< fa code >}}]{style="color: lightgray"}  | [{{< fa laptop-code >}}]{style="color: lightgray"} | <i class="fa fa-book" style="color: lightgray; font-weight: bold;"></i> |

#### Take Home Exam

::: {.callout-note icon=false}
## {{< fa file-pen >}} Take Home Exam

**Window:** May 28 19:00 — June 11 23:59 (two weeks)

**Distribution:** via GitHub Classroom, like the weekly homework assignments.

**Submission:** the version of your repository at the moment the deadline passes (i.e., your last push before June 11 23:59) will be graded.

**What to expect:** you will receive a dataset, contextual background, and a research question, and are expected to conduct a full empirical analysis on your own — covering data exploration, model formulation and justification, estimation, and interpretation — submitted as a reproducible repository with a rendered PDF.

Detailed grading criteria and the late submission policy will be announced together with the exam.
:::